sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "lts/*"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g @angular/cli

script:
  - ng build --build-optimizer --aot --prod
  - ng test  --watch=false --code-coverage --browsers ChromeHeadless
  - ng e2e --protractor-config atdd/conf/protractor.conf.ci.js --webdriver-update false
