sudo: required
os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master
    - develop
cache:
  directories:
    - node_modules
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g @angular/cli
install:
  - npm install
script:
  - ng test --watch=false --code-coverage --browsers=ChromeHeadless
  - ng e2e
  - ng build --build-optimizer --aot --prod
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false